services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: northwind
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
      - ./northwind.sql:/docker-entrypoint-initdb.d/northwind.sql
      - ./files:/files
    ports:
      - 55432:5432

  pgadmin:
    image: michalhosna/adminer
    environment:
      ADMINER_DB: northwind
      ADMINER_DRIVER: pgsql
      ADMINER_PASSWORD: postgres
      ADMINER_SERVER: db:5432
      ADMINER_USERNAME: postgres
      ADMINER_AUTOLOGIN: 1
    ports:
      - 8080:8080


volumes:
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local
